<a href="https://colab.research.google.com/github/ashu6196/Cyber-Threat-Detection/blob/main/Autoencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from joblib import dump, load
from sklearn.metrics import accuracy_score, f1_score, precision_score,recall_score
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from itertools import cycle
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import sklearn.metrics as metrics

In [ ]:
df = pd.read_csv('/content/gdrive/MyDrive/nsl-kdd/KDDTrain+.txt', header=None)
df.head()

   0    1         2   3    4     5   ...    37    38    39    40       41  42
0   0  tcp  ftp_data  SF  491     0  ...  0.00  0.00  0.05  0.00   normal  20
1   0  udp     other  SF  146     0  ...  0.00  0.00  0.00  0.00   normal  15
2   0  tcp   private  S0    0     0  ...  1.00  1.00  0.00  0.00  neptune  19
3   0  tcp      http  SF  232  8153  ...  0.03  0.01  0.00  0.01   normal  21
4   0  tcp      http  SF  199   420  ...  0.00  0.00  0.00  0.00   normal  21

[5 rows x 43 columns]

In [ ]:
qp = pd.read_csv('/content/gdrive/MyDrive/nsl-kdd/KDDTest+.txt', header=None)
qp.head()

   0     1         2     3      4   5   ...   37   38    39    40       41  42
0   0   tcp   private   REJ      0   0  ...  0.0  0.0  1.00  1.00  neptune  21
1   0   tcp   private   REJ      0   0  ...  0.0  0.0  1.00  1.00  neptune  21
2   2   tcp  ftp_data    SF  12983   0  ...  0.0  0.0  0.00  0.00   normal  21
3   0  icmp     eco_i    SF     20   0  ...  0.0  0.0  0.00  0.00    saint  15
4   1   tcp    telnet  RSTO      0  15  ...  0.0  0.0  0.83  0.71    mscan  11

[5 rows x 43 columns]

In [ ]:
df.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'class', 'difficulty_level']
df.head()

   duration protocol_type  ...    class difficulty_level
0         0           tcp  ...   normal               20
1         0           udp  ...   normal               15
2         0           tcp  ...  neptune               19
3         0           tcp  ...   normal               21
4         0           tcp  ...   normal               21

[5 rows x 43 columns]

In [ ]:
qp.columns = ['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
'num_access_files', 'num_outbound_cmds', 'is_host_login',
'is_guest_login', 'count', 'srv_count', 'serror_rate',
'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
'dst_host_srv_count', 'dst_host_same_srv_rate','dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
'dst_host_srv_rerror_rate', 'class', 'difficulty_level']
qp.head()

   duration protocol_type  ...    class difficulty_level
0         0           tcp  ...  neptune               21
1         0           tcp  ...  neptune               21
2         2           tcp  ...   normal               21
3         0          icmp  ...    saint               15
4         1           tcp  ...    mscan               11

[5 rows x 43 columns]

In [ ]:
lst_names = df.columns # returns a list of column names
lst_names

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class', 'difficulty_level'],
      dtype='object')

In [ ]:
testlst_names = qp.columns
testlst_names

Index(['duration', 'protocol_type', 'service', 'flag', 'src_bytes',
       'dst_bytes', 'land', 'wrong_fragment', 'urgent', 'hot',
       'num_failed_logins', 'logged_in', 'num_compromised', 'root_shell',
       'su_attempted', 'num_root', 'num_file_creations', 'num_shells',
       'num_access_files', 'num_outbound_cmds', 'is_host_login',
       'is_guest_login', 'count', 'srv_count', 'serror_rate',
       'srv_serror_rate', 'rerror_rate', 'srv_rerror_rate', 'same_srv_rate',
       'diff_srv_rate', 'srv_diff_host_rate', 'dst_host_count',
       'dst_host_srv_count', 'dst_host_same_srv_rate',
       'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
       'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
       'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
       'dst_host_srv_rerror_rate', 'class', 'difficulty_level'],
      dtype='object')

In [ ]:
df.isnull().values.any()

False

In [ ]:
qp.isnull().values.any()

False

In [ ]:
df['class']

0          normal
1          normal
2         neptune
3          normal
4          normal
           ...
125968    neptune
125969     normal
125970     normal
125971    neptune
125972     normal
Name: class, Length: 125973, dtype: object

In [ ]:
cols = ['protocol_type','service','flag']
cols

['protocol_type', 'service', 'flag']

In [ ]:
def one_hot(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with one-hot encoding
    """
    for each in cols:
        dummies = pd.get_dummies(df[each], prefix=each, drop_first=False)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop(each, 1)
    return df

In [ ]:
combined_data = pd.concat([df,qp])

In [ ]:
combined_data = one_hot(combined_data,cols)

In [ ]:
new_train_df = combined_data.iloc[:125973]
new_test_df = combined_data.iloc[125973:]

In [ ]:
new_train_df

        duration  src_bytes  dst_bytes  ...  flag_S3  flag_SF  flag_SH
0              0        491          0  ...        0        1        0
1              0        146          0  ...        0        1        0
2              0          0          0  ...        0        0        0
3              0        232       8153  ...        0        1        0
4              0        199        420  ...        0        1        0
...          ...        ...        ...  ...      ...      ...      ...
125968         0          0          0  ...        0        0        0
125969         8        105        145  ...        0        1        0
125970         0       2231        384  ...        0        1        0
125971         0          0          0  ...        0        0        0
125972         0        151          0  ...        0        1        0

[125973 rows x 124 columns]

In [ ]:
tmp = new_train_df.pop('class')

In [ ]:
classlist = []
check1 = ("apache2","back","land","neptune","mailbomb","pod","processtable","smurf","teardrop","udpstorm","worm",
         "ipsweep","mscan","nmap","portsweep","saint","satan",
         "buffer_overflow","loadmodule","perl","ps","rootkit","sqlattack","xterm",
         "ftp_write","guess_passwd","httptunnel","imap","multihop","named","phf","sendmail","Snmpgetattack","spy","snmpguess","warezclient","warezmaster","xlock","xsnoop")

In [ ]:
for item in tmp:
    if item in check1:
        classlist.append(1)
    else:
        classlist.append(0)

In [ ]:
new_train_df.head()

   duration  src_bytes  dst_bytes  land  ...  flag_S2  flag_S3  flag_SF  flag_SH
0         0        491          0     0  ...        0        0        1        0
1         0        146          0     0  ...        0        0        1        0
2         0          0          0     0  ...        0        0        0        0
3         0        232       8153     0  ...        0        0        1        0
4         0        199        420     0  ...        0        0        1        0

[5 rows x 123 columns]

In [ ]:
testtmp = new_test_df.pop('class')

In [ ]:
testclasslist = []
testcheck1 = ("apache2","back","land","neptune","mailbomb","pod","processtable","smurf","teardrop","udpstorm","worm",
             "ipsweep","mscan","nmap","portsweep","saint","satan",
             "buffer_overflow","loadmodule","perl","ps","rootkit","sqlattack","xterm",
              "ftp_write","guess_passwd","httptunnel","imap","multihop","named","phf","sendmail","Snmpgetattack","spy","snmpguess","warezclient","warezmaster","xlock","xsnoop")





for item in testtmp:
    if item in check1:
        classlist.append(1)
    else:
        classlist.append(0)

In [ ]:
new_test_df["Class"] = testclasslist

ValueError: ignored

In [ ]:
def normalize(df, cols):
    """
    @param df pandas DataFrame
    @param cols a list of columns to encode
    @return a DataFrame with normalized specified features
    """
    result = df.copy() # do not touch the original df
    for feature_name in cols:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        if max_value > min_value:
            result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [ ]:
train_df = normalize(new_train_df,new_train_df.columns)
train_df.head()

   duration     src_bytes     dst_bytes  ...  flag_S3  flag_SF  flag_SH
0       0.0  3.558064e-07  0.000000e+00  ...      0.0      1.0      0.0
1       0.0  1.057999e-07  0.000000e+00  ...      0.0      1.0      0.0
2       0.0  0.000000e+00  0.000000e+00  ...      0.0      0.0      0.0
3       0.0  1.681203e-07  6.223962e-06  ...      0.0      1.0      0.0
4       0.0  1.442067e-07  3.206260e-07  ...      0.0      1.0      0.0

[5 rows x 123 columns]